### ISSUE TITLE
Create WebFlux + Boot example 

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-hateoas-examples#27]

**Comment by SchlammSpringer** [comment]
That would be very interessting.
Especially it looks like that 
`X-Forwarded-Prefix:`
is no more added to Link in such a scenario

```yaml
spring:
  main:
    web-application-type: reactiveserver:
server:
  forward-headers-strategy: native

```
